version: '2'
services:
    jdl1-app:
        image: jdl1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jdl1-mysql:3306/jdl1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jdl1-mysql:
        extends:
            file: mysql.yml
            service: jdl1-mysql
